name: CI

on:
  push:
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: dejwcake/node24:1
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm run format:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: dejwcake/node24:1
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm run lint

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    container:
      image: dejwcake/node24:1
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm run lint:style

  vitest:
    name: Vitest
    needs: [prettier, eslint, stylelint]
    runs-on: ubuntu-latest
    container:
      image: dejwcake/node24:1
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm test
